language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
branches:
  only:
  - master
  - stable
deploy:
  provider: heroku
  api_key:
    secure: 3d1dcf89-2035-4fe9-b681-9ebad93b93bf
  app: glacial-depths-32500
  on:
    repo: anthonypagano/hotcold
